# Generated by Django 5.2.3 on 2025-09-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jerseys', 'Jerseys'), ('shoes', 'Shoes'), ('posters', 'Posters'), ('miniatures', 'Miniatures')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
