# Generated by Django 5.2.3 on 2025-09-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_is_featured_product_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('miniatures', 'Miniatures'), ('posters', 'Posters'), ('jerseys', 'Jerseys')], max_length=20),
        ),
    ]
