# Generated by Django 5.2.3 on 2025-09-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Jerseys', 'Jerseys'), ('Posters', 'Posters'), ('Miniatures', 'Miniatures')], max_length=20),
        ),
    ]
