# Generated by Django 5.2.3 on 2025-09-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Posters', 'Posters'), ('Shoes', 'Shoes'), ('Jerseys', 'Jerseys'), ('Miniatures', 'Miniatures')], max_length=20),
        ),
    ]
