# Generated by Django 5.2.3 on 2025-09-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_is_featured_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Jerseys', 'Jerseys'), ('Miniatures', 'Miniatures'), ('Shoes', 'Shoes'), ('Posters', 'Posters')], max_length=20),
        ),
    ]
