# Generated by Django 5.2.3 on 2025-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_is_featured_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Posters', 'Posters'), ('Miniatures', 'Miniatures'), ('Shoes', 'Shoes'), ('Jerseys', 'Jerseys')], max_length=20),
        ),
    ]
