# Generated by Django 5.2.3 on 2025-09-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_add_product_sold_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Posters', 'Posters'), ('Jerseys', 'Jerseys'), ('Miniatures', 'Miniatures')], max_length=20),
        ),
    ]
