# Generated by Django 5.2.6 on 2025-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_user_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Miniatures', 'Miniatures'), ('Posters', 'Posters'), ('Shoes', 'Shoes'), ('Jerseys', 'Jerseys')], max_length=20),
        ),
    ]
