# Generated by Django 5.2.6 on 2025-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Posters', 'Posters'), ('Jerseys', 'Jerseys'), ('Shoes', 'Shoes'), ('Miniatures', 'Miniatures')], max_length=20),
        ),
    ]
